[include.optional]
files = ["noctalia.toml"]

[include]
files = [
    "cfg/animation.toml",
    "cfg/autostart.toml",
    # "cfg/display.toml",
    "cfg/outputs.toml",
    "cfg/input.toml",
    "cfg/keybinds.toml",
    "cfg/layout.toml",
    "cfg/misc.toml",
    "cfg/rules.toml",
]

# Override overview colors
[overview]
workspace_wallpaper = false
background_blur = false


[colors.overview]
background_tint = "#00000000"
workspace_background = "#00000000"
